# Generated by Django 4.2.1 on 2023-07-04 06:55

import django_extensions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_favorite_options_alter_tag_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Выберите цвет для тега в HEX, например, #49B64E', max_length=7, validators=[django_extensions.validators.HexValidator(length=7)], verbose_name='Цвет в HEX'),
        ),
    ]
